### ISSUE TITLE
Docker compose file missing?

### ISSUE THREAD

**Issue by Messhias** [Chris7T/todo-list-api#1]
When we try to execute the command `docker compose up -d nginx postgres` we get the following error:
<img width="1440" alt="Screenshot 2022-01-06 at 12 44 28" src="https://user-images.githubusercontent.com/1161283/148384873-defe860b-19f4-49df-80b4-c806517f85f8.png">

**Comment by Chris7T** [comment]
I'm sorry, i forgot to remove the ".env" from the ".gitignore" file. You can try again, the files has pushed.

**Comment by Messhias** [comment]
> I'm sorry, I forgot to remove the ".env" from the ".gitignore" file. You can try again, the files have been pushed.

Christian, the docker is missing, the command `docker-compose up -d nginx postgres` is not working as you can see in the screenshot, so it's not possible to reproduce your test, this is nothing with .env files.

**Comment by Chris7T** [comment]
Are you running command in laradock folder ?

**Comment by Messhias** [comment]
> Are you running command in laradock folder ?

Hi, no. 

You readme.md is not telling to us that we need to run it on laradock folder.

**Comment by Chris7T** [comment]
I understand, im sorry, run the command in laradock folder.
